---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: applications
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: ssh://git@github.com/gitops-tech/example-environment

