apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: example-application
  namespace: default
spec:
  interval: 5m0s
  path: ./applications/example-application
  prune: true
  sourceRef:
    kind: GitRepository
    name: applications
  validation: client